### ISSUE TITLE
Suggestions 

### ISSUE THREAD

**Issue by rfay** [GsTYPO3/introduction#3]
It all worked great for me.

Possible suggestions, things to think about:

1. Don't put the `name:` in the config.yaml. that way it will take the directory name, and won't be tied to a specific name that might conflict with other things.
2. Consider omitting the timezone, as that makes it a very provincial recipe.
3. Consider renaming the repo, perhaps to "typo3-introduction" so that when they clone it it has an understandable name.
4. Remove .ddev/commands/web/typo3 as it is now a standard feature in ddev (and a warning emits as a result)

**Comment by gilbertsoft** [comment]
Thanks for the input! Fully agree on the points 1-3.

The typo3 command has here an other function, it's to change the core version. I've have choosen this name because if you have the TYPO3-Console installed it's recommended to only use typo3cms and not longer rely on typo3. But yes, this could be confusing but I did not find a better name so far...
